export const SEARCH_TEXT = 'SEARCH_TEXT';
export const FETCH_CRYPTOS = 'FETCH_CRYPTOS';
export const LOADING_SPINNER = 'LOADING_SPINNER';
export const REFRESH_CRYPTOS = 'REFRESH_CRYPTOS';
export const COUNTDOWN = 'COUNTDOWN';
